"""SUPERSEDED by train_asl_v2.py -- kept for reference only.

This is the v1 ASL model: 64 hidden units, no input normalization. The
committed weights in mem/ come from train_asl_v2.py (128 hidden, global
mean/std normalization folded into layer 1 at export). Running this script
overwrites mlp_asl_fp32.pt with a model the RTL parameters do not match.

Originally: Stage 1 (ASL variant): Train the float32 reference MLP.

    784 -> 64 -> 24

Same architecture as the MNIST version; only the output width changes
(10 digits -> 24 ASL letters). The hardware datapath is identical except
for layer-2 dimensions and address ranges.

Dataset: Sign Language MNIST (Kaggle: datamunge/sign-language-mnist)
Place sign_mnist_train.csv and sign_mnist_test.csv in ./data/

KNOWN CAVEAT: this dataset was generated by augmenting a small set of
original photographs, and train/test share that origin. Accuracy here is
optimistic and is NOT a measure of generalization to new signers. Report
it with that context.
"""

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

torch.manual_seed(0)

HIDDEN = 64
EPOCHS = 12
BATCH = 128
LR = 1e-3

TRAIN_CSV = "./data/sign_mnist_train.csv"
TEST_CSV = "./data/sign_mnist_test.csv"

# Raw labels run 0..25 but 9 (J) and 25 (Z) never appear -- both require
# motion. Left as-is, the output layer would carry two neurons that can
# never fire: wasted MACs, wasted BRAM, and a confusing confusion matrix.
# Remap to a contiguous 0..23.
RAW_LABELS = [i for i in range(26) if i not in (9, 25)]
RAW_TO_IDX = {raw: i for i, raw in enumerate(RAW_LABELS)}
IDX_TO_LETTER = [chr(ord("A") + raw) for raw in RAW_LABELS]
NUM_CLASSES = len(RAW_LABELS)  # 24


class MLP(nn.Module):
    def __init__(self, hidden=HIDDEN, n_out=NUM_CLASSES):
        super().__init__()
        self.fc1 = nn.Linear(784, hidden)
        self.fc2 = nn.Linear(hidden, n_out)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = x.view(-1, 784)
        x = self.relu(self.fc1(x))
        return self.fc2(x)


def load_csv(path):
    """CSV layout: col 0 = label, cols 1..784 = pixel values 0-255."""
    raw = np.loadtxt(path, delimiter=",", skiprows=1, dtype=np.int32)
    labels_raw = raw[:, 0]
    pixels = raw[:, 1:].astype(np.float32)

    unknown = set(labels_raw.tolist()) - set(RAW_TO_IDX)
    if unknown:
        raise ValueError(f"unexpected labels in {path}: {sorted(unknown)}")

    labels = np.array([RAW_TO_IDX[v] for v in labels_raw], dtype=np.int64)

    # Scale to [0,1] to match the MNIST script. Deliberately no mean/std
    # normalization: on hardware the input is a raw uint8 pixel, and keeping
    # the training domain a plain scaling of that makes input quantization
    # a no-op.
    pixels /= 255.0

    return TensorDataset(torch.from_numpy(pixels), torch.from_numpy(labels))


@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    correct = total = 0
    for x, y in loader:
        correct += (model(x).argmax(dim=1) == y).sum().item()
        total += y.numel()
    return correct / total


@torch.no_grad()
def per_class_accuracy(model, loader):
    model.eval()
    hit = np.zeros(NUM_CLASSES, dtype=np.int64)
    seen = np.zeros(NUM_CLASSES, dtype=np.int64)
    for x, y in loader:
        pred = model(x).argmax(dim=1)
        for cls in range(NUM_CLASSES):
            mask = y == cls
            seen[cls] += mask.sum().item()
            hit[cls] += (pred[mask] == cls).sum().item()
    return hit, seen


def main():
    train_ds = load_csv(TRAIN_CSV)
    test_ds = load_csv(TEST_CSV)
    print(f"train {len(train_ds)} samples, test {len(test_ds)} samples, "
          f"{NUM_CLASSES} classes")

    train_loader = DataLoader(train_ds, batch_size=BATCH, shuffle=True)
    test_loader = DataLoader(test_ds, batch_size=1000)

    model = MLP()
    opt = torch.optim.Adam(model.parameters(), lr=LR)
    lossfn = nn.CrossEntropyLoss()

    for epoch in range(1, EPOCHS + 1):
        model.train()
        for x, y in train_loader:
            opt.zero_grad()
            lossfn(model(x), y).backward()
            opt.step()
        print(f"epoch {epoch:2d}  test acc {evaluate(model, test_loader)*100:.2f}%")

    acc = evaluate(model, test_loader)
    print(f"\nFP32 baseline accuracy: {acc*100:.2f}%   <-- record this number")
    print("  (dataset is augmentation-correlated; treat as optimistic)")

    torch.save(model.state_dict(), "mlp_asl_fp32.pt")
    print("saved mlp_asl_fp32.pt")

    print("\nweight ranges -- these set the per-layer quantization scales:")
    for name, p in model.named_parameters():
        print(f"  {name:12s} shape {tuple(p.shape)}  "
              f"min {p.min():+.4f}  max {p.max():+.4f}")

    # Worth a look: if one letter is far below the rest, that's usually a
    # visually ambiguous sign (M/N/S/T are the usual suspects) rather than
    # a bug. Good material for the writeup.
    hit, seen = per_class_accuracy(model, test_loader)
    print("\nper-class accuracy:")
    for cls in range(NUM_CLASSES):
        pct = 100.0 * hit[cls] / seen[cls] if seen[cls] else float("nan")
        print(f"  {cls:2d}  {IDX_TO_LETTER[cls]}  {pct:6.2f}%  (n={seen[cls]})")


if __name__ == "__main__":
    main()
